language: python

python:
  - "2.7"

service:
  - docker

script:
  - docker-compose -v
  - docker build -t javiersanp/prueba .
  - docker run --rm javiersanp/prueba /bin/bash -c "python -m unittest discover"
  - docker image ls
  - echo $DOCKER_USERNAME

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
