language: python

python:
  - "2.7"

service:
  - docker

script:
  - python -m unittest discover
  - docker build -t javiersanp/prueba .
  - docker run --rm javiersanp/prueba /bin/bash -c "python -m unittest discover"

deploy:
  provider: script
  script:
    - docker image ls
