language: python

python:
  - "2.7"

service:
  - docker

script:
  - python -m unittest discover
  - docker build -t javiersanp/prueba .
  - docker run -it --rm javiersanp/prueba bash -c "python -m unittest discover"

deploy:
  - docker push javiersanp/prueba
